#! /bin/env sh

printf ">>> Defining Cross directory tree.\n"
_CROSS_DIR="`pwd`"
_CROSS_DOWNLOAD_DIR="$_CROSS_DIR/download"
_CROSS_SOURCE_DIR="/tmp/cross-src"
_CROSS_PATCH_DIR="$_CROSS_DIR/patches"
_CROSS_BUILD_DIR="$_CROSS_DIR/build"
_CROSS_PREREQ_DIR="$_CROSS_DIR/prerequisites"
_CROSS_STAGE_DIR="$_CROSS_DIR/stage"
_CROSS_PACKAGE_DIR="$_CROSS_DIR/packages"
_CROSS_LOG_DIR="$_CROSS_DIR/logs"

printf ">>> Creating Cross directory tree.\n"
mkdir -p "$_CROSS_DOWNLOAD_DIR"
mkdir -p "$_CROSS_SOURCE_DIR"
mkdir -p "$_CROSS_BUILD_DIR"
mkdir -p "$_CROSS_PACKAGE_DIR"
mkdir -p "$_CROSS_LOG_DIR"
mkdir -p "$_CROSS_PREREQ_DIR"
