#! /usr/bin/env sh

# Prerequisite libraries
_CROSS_VERSION_GMP="5.1.2"
_CROSS_VERSION_MPFR="3.1.2"
_CROSS_VERSION_MPC="1.0.1"
_CROSS_VERSION_PPL="1.0"
_CROSS_VERSION_ISL="0.11.2"
_CROSS_VERSION_CLOOG="0.18.0"
_CROSS_VERSION_LIBICONV="1.14"
_CROSS_VERSION_EXPAT="2.1.0"

_CROSS_VERSION_MINGW_W64="2.0.8"

_CROSS_VERSION_BINUTILS="2.23.2"
_CROSS_VERSION_GCC="4.7.2"
_CROSS_VERSION_LLVM="3.3"

_CROSS_VERSION_GDB="7.6"
_CROSS_VERSION_MAKE="3.82"

_CROSS_PACKAGE_VERSION="--with-pkgversion=rubenvb --with-bugurl=mingw-w64-public@lists.sourceforge.net"
