#! /usr/bin/env sh

# Prerequisite libraries
_CROSS_VERSION_GMP="5.1.3"
_CROSS_VERSION_MPFR="3.1.2"
_CROSS_VERSION_MPC="1.0.1"
_CROSS_VERSION_PPL="1.1"
_CROSS_VERSION_ISL="0.11.1" # GCC infrastructure version
_CROSS_VERSION_CLOOG="0.18.1"
_CROSS_VERSION_LIBICONV="1.14"
_CROSS_VERSION_EXPAT="2.1.0"

_CROSS_VERSION_MINGW_W64="v3.0.0"

_CROSS_VERSION_BINUTILS="2.24"
_CROSS_VERSION_GCC="4.6.3"
_CROSS_VERSION_LLVM="3.3"

_CROSS_VERSION_GDB="7.6.2"
_CROSS_VERSION_MAKE="3.82"

_CROSS_PACKAGE_VERSION="--with-pkgversion=rubenvb --with-bugurl=github.com/rubenvb/cross/issues"
